name: VyOS Rolling Release Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Clone VyOS repository
    - name: Clone VyOS repository
      run: |
        git clone --branch current https://github.com/vyos/vyos-build.git
        cd vyos-build

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          curl \
          build-essential \
          python3 \
          python3-pip \
          qemu-kvm \
          libvirt-daemon-system \
          libvirt-clients \
          virt-manager \
          squashfs-tools \
          xorriso \
          live-build \
          debootstrap \
          pbuilder \
          devscripts \
          python3-pystache \
          python3-git \
          python3-pip
          pip3 install gitpython psutil jinja2 tomli pystache pyyaml requests jsonschema pytest mock pytest-mock click tabulate netaddr paramiko scapy cryptography pyroute2


    # Configure Kernel for Hyper-V
    - name: Configure Kernel for Hyper-V
      run: |
        cd vyos-build
        echo 'CONFIG_HYPERV=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_VMBUS=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_STORAGE=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_NET=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_BALLOON=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_UTILS=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_KEYBOARD=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_PARAVIRT=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_X86_HYPERV_TIMER=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_TSCPAGE=y' >> data/live-build-config/package-lists/config.kernel
        echo 'CONFIG_HYPERV_IOMMU=y' >> data/live-build-config/package-lists/config.kernel
    - name: Configure live-build and Update Mirrors
      run: |
        cd vyos-build
        sudo lb clean
        sudo lb config \
          --distribution focal \
          --architectures amd64 \
          --mirror-bootstrap http://archive.ubuntu.com/ubuntu \
          --archive-areas "main contrib non-free"

    # Build VyOS ISO
    - name: Build VyOS ISO
      run: |
        cd vyos-build
        sudo --preserve-env ./build-vyos-image \
          --architecture amd64 \
          --build-by GitHub-Actions \
          --build-type release  \
          --version $(date +%Y%m%d%H%M%S) \
          generic
        mv build/*.iso ./vyos-rolling.iso

    # Upload VyOS ISO
    - name: Upload VyOS ISO
      uses: actions/upload-artifact@v3
      with:
        name: vyos-rolling-iso
        path: vyos-rolling.iso
